---
- name: Verificación de Infraestructura Completa
  hosts: all
  become: yes
  gather_facts: no

  tasks:

    # ========================
    # 1. Comprobar Apache en frontends
    # ========================
    - name: Comprobar Apache en los frontends
      ansible.builtin.systemd:
        name: apache2
        state: started
      when: inventory_hostname in groups['frontend']
      register: apache_status

    - name: Mostrar estado de Apache
      debug:
        msg: "Apache está funcionando en {{ inventory_hostname }}"
      when: apache_status is defined and apache_status.status is defined


    # ========================
    # 2. Comprobar MySQL en backends
    # ========================
    - name: Comprobar MySQL en los backends
      ansible.builtin.systemd:
        name: mysql
        state: started
      when: inventory_hostname in groups['backend']
      register: mysql_status

    - name: Mostrar estado MySQL
      debug:
        msg: "MySQL está funcionando en {{ inventory_hostname }}"
      when: mysql_status is defined and mysql_status.status is defined


    # ========================
    # 3. Comprobar NFS Server
    # ========================
    - name: Comprobar servicio NFS en servidor
      ansible.builtin.systemd:
        name: nfs-kernel-server
        state: started
      when: inventory_hostname in groups['nfs']
      register: nfs_status

    - name: Mostrar estado NFS
      debug:
        msg: "NFS operativo en {{ inventory_hostname }}"
      when: nfs_status is defined and nfs_status.status is defined


    # ========================
    # 4. Comprobar NFS Client (mount)
    # ========================
    - name: Verificar montaje NFS en frontends
      shell: "mount | grep '/var/www/html/media'"
      when: inventory_hostname in groups['frontend']
      register: nfs_mount
      failed_when: nfs_mount.rc != 0

    - name: Mostrar resultado NFS Client
      debug:
        var: nfs_mount.stdout
      when: nfs_mount.stdout is defined


    # ========================
    # 5. Comprobar Balanceador NGINX
    # ========================
    - name: Comprobar servicio Nginx en load balancer
      ansible.builtin.systemd:
        name: nginx
        state: started
      when: inventory_hostname in groups['lb']
      register: nginx_status

    - name: Mostrar estado Nginx
      debug:
        msg: "Nginx funcionando correctamente en {{ inventory_hostname }}"
      when: nginx_status is defined and nginx_status.status is defined
