---
- name: Cargar variables globales
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/variables.yml
  tasks:
    - debug:
        msg: "Variables cargadas correctamente"

- import_playbook: playbooks/setup_backend.yml
- import_playbook: playbooks/deploy_backend.yml
- import_playbook: playbooks/create_admin_user.yml
- import_playbook: playbooks/setup_nfs.yml
- import_playbook: playbooks/setup_nfs_client.yml
- import_playbook: playbooks/setup_frontend.yml
- import_playbook: playbooks/deploy_frontend.yml
- import_playbook: playbooks/setup_loadbalancer.yml
- import_playbook: playbooks/setup_letsencrypt_https.yml
