---
- name: Poblar datos demo para toda la clínica
  hosts: backend1
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    ###############################################################
    # CATÁLOGOS BÁSICOS
    ###############################################################

    - name: Insertar categorías de empleados
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO CategoriasEmpleados (nombre, descripcion) VALUES
          ('Médico Estético', 'Especialista en tratamientos faciales y corporales'),
          ('Enfermería', 'Soporte clínico y asistencial'),
          ('Recepción', 'Atención al cliente y administración'),
          ('Marketing', 'Gestión de campañas y redes sociales'),
          ('Dirección', 'Gestión de la clínica')
          ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

    - name: Insertar categorías de tratamientos
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO CategoriasTratamientos (nombre, descripcion) VALUES
          ('Facial', 'Tratamientos faciales y rejuvenecimiento'),
          ('Corporal', 'Tratamientos corporales y remodelación'),
          ('Láser', 'Depilación y otros tratamientos láser'),
          ('Anti-edad', 'Tratamientos orientados al envejecimiento'),
          ('Bienestar', 'Masajes y tratamientos relajantes')
          ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

    - name: Insertar especialidades
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Especialidades (nombre, descripcion) VALUES
          ('Medicina Estética', 'Tratamientos médicos no invasivos'),
          ('Dermatología', 'Cuidado de la piel'),
          ('Láser', 'Manejo de equipos láser'),
          ('Nutrición', 'Planes nutricionales asociados a tratamientos'),
          ('Fisioterapia', 'Tratamientos corporales y rehabilitación')
          ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

    - name: Insertar salas demo
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Salas (nombre, tipo, capacidad) VALUES
          ('Sala 1 - Facial', 'Tratamiento', 1),
          ('Sala 2 - Corporal', 'Tratamiento', 1),
          ('Cabina Láser', 'Láser', 1),
          ('Consulta Médica', 'Consulta', 2),
          ('Sala Relax', 'Cabina', 1)
          ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

    - name: Insertar proveedores demo
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Proveedores (nombre, telefono, correo, direccion) VALUES
          ('Dermacosmetics S.L.', '+34 911111111', 'contacto@dermacosmetics.es', 'Madrid'),
          ('Estética Global', '+34 922222222', 'info@esteticaglobal.es', 'Barcelona'),
          ('Láser ProTech', '+34 933333333', 'ventas@laserprotech.com', 'Valencia'),
          ('BioSkin Pharma', '+34 944444444', 'soporte@bioskinpharma.es', 'Sevilla')
          ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

    ###############################################################
    # INVENTARIO
    ###############################################################

    - name: Insertar inventario demo
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Inventario (nombre, tipo, stock_actual, unidad, costo_unitario, proveedor_id)
          SELECT * FROM (
            SELECT 'Crema hidratante facial', 'insumo', 80, 'uds', 12.50, 1 UNION ALL
            SELECT 'Ampollas vitamina C', 'insumo', 40, 'uds', 18.00, 1 UNION ALL
            SELECT 'Relleno ácido hialurónico', 'producto', 25, 'viales', 95.00, 2 UNION ALL
            SELECT 'Equipo láser depilación', 'equipamiento', 2, 'unidad', 8000.00, 3 UNION ALL
            SELECT 'Guantes nitrilo', 'insumo', 300, 'caja', 5.50, 4 UNION ALL
            SELECT 'Mascarilla colágeno', 'insumo', 60, 'uds', 8.90, 2 UNION ALL
            SELECT 'Sérum anti-edad', 'producto', 35, 'uds', 35.00, 1 UNION ALL
            SELECT 'Toallas desechables', 'insumo', 200, 'paquete', 10.00, 4
          ) AS tmp;

    ###############################################################
    # TRATAMIENTOS
    ###############################################################

    - name: Insertar tratamientos demo
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Tratamientos (nombre, descripcion, precio, duracion_min, categoria_id, requiere_sala)
          VALUES
            ('Limpieza facial profunda', 'Limpieza con extracción', 60.00, 60, 1, 1),
            ('Peeling químico suave', 'Renovación superficial', 80.00, 45, 1, 1),
            ('Masaje reductor', 'Zonas localizadas', 70.00, 60, 2, 1),
            ('Radiofrecuencia facial', 'Firmeza y colágeno', 90.00, 50, 4, 1),
            ('Láser piernas completas', 'Depilación láser', 150.00, 75, 3, 1),
            ('Láser axilas', 'Sesión simple', 50.00, 30, 3, 1),
            ('Anti-edad premium', 'Protocolo combinado', 180.00, 90, 4, 1),
            ('Masaje aromático', 'Relajación', 55.00, 50, 5, 1),
            ('LPG corporal', 'Remodelante', 95.00, 60, 2, 1),
            ('Láser manchas faciales', 'Tratamiento puntual', 130.00, 45, 3, 1)
          ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);

    ###############################################################
    # EMPLEADOS
    ###############################################################

    - name: Insertar empleados demo
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Empleados (nombre, apellido, fecha_ingreso, telefono, email, categoria_id, activo)
          VALUES
            ('María', 'García López', '2021-03-15', '+34 600111111', 'maria@clinica.com', 1, 1),
            ('Laura', 'Fernández Ruiz', '2022-01-10', '+34 600222222', 'laura@clinica.com', 1, 1),
            ('Ana', 'Santos Pérez', '2020-09-01', '+34 600333333', 'ana@clinica.com', 2, 1),
            ('Carmen', 'Martín Díaz', '2019-05-20', '+34 600444444', 'carmen@clinica.com', 3, 1),
            ('Lucía', 'Navarro Gil', '2023-02-01', '+34 600555555', 'lucia@clinica.com', 4, 1),
            ('Sofía', 'Romero Sáez', '2018-11-11', '+34 600666666', 'sofia@clinica.com', 5, 1)
          ON DUPLICATE KEY UPDATE email = VALUES(email);

    ###############################################################
    # CLIENTES (600)
    ###############################################################

    - name: Insertar 600 clientes aleatorios
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Clientes (dni, nombre, apellido, fecha_nacimiento, edad, genero,
                                telefono, correo, direccion, fecha_registro, origen_cliente)
          SELECT
            CONCAT('DNI', LPAD(FLOOR(RAND()*90000000)+10000000, 8, '0')),
            CONCAT('Nombre', FLOOR(RAND()*500)),
            CONCAT('Apellido', FLOOR(RAND()*500)),
            DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND()*40+18) YEAR),
            FLOOR(RAND()*40+18),
            ELT(FLOOR(RAND()*3)+1,'Hombre','Mujer','Otro'),
            CONCAT('+34 6', LPAD(FLOOR(RAND()*900000), 6, '0')),
            CONCAT('cliente', FLOOR(RAND()*99999), '@mail.com'),
            CONCAT('Calle ', FLOOR(RAND()*200), ' Madrid'),
            DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND()*365) DAY),
            ELT(FLOOR(RAND()*6)+1,'Google','Instagram','Recomendacion','Web','Publicidad','Otro')
          FROM dual
          LIMIT 600;

    ###############################################################
    # CITAS (800)
    ###############################################################

    - name: Insertar 800 citas aleatorias
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Citas (cliente_id, empleado_id, tratamiento_id, sala_id,
                             fecha_cita, hora_cita, estado, observaciones)
          SELECT
            FLOOR(RAND()*600)+1,
            FLOOR(RAND()*6)+1,
            FLOOR(RAND()*10)+1,
            FLOOR(RAND()*5)+1,
            DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND()*180) DAY),
            TIME(CONCAT(LPAD(FLOOR(RAND()*8+9), 2, '0'), ':', IF(RAND()>0.5,'00','30'), ':00')),
            ELT(FLOOR(RAND()*5)+1,'pendiente','confirmada','realizada','cancelada','reprogramada'),
            'Cita generada automáticamente'
          FROM dual
          LIMIT 800;

    ###############################################################
    # PAGOS
    ###############################################################

    - name: Insertar pagos (600 citas)
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Pagos (cita_id, metodo_pago, monto, fecha_pago)
          SELECT
            c.cita_id,
            ELT(FLOOR(RAND()*4)+1,'efectivo','tarjeta','transferencia','bizum'),
            ROUND((SELECT precio FROM Tratamientos t 
                   WHERE t.tratamiento_id = c.tratamiento_id)
                   * (1 + (RAND()-0.5)/10),2),
            CONCAT(c.fecha_cita, ' ', c.hora_cita)
          FROM Citas c
          WHERE c.estado IN ('confirmada','realizada')
          LIMIT 600;

    ###############################################################
    # VALORACIONES
    ###############################################################

    - name: Insertar 150 valoraciones
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO Valoraciones (cita_id, puntuacion, comentario)
          SELECT
            cita_id,
            FLOOR(RAND()*3)+3,
            'Valoración generada automáticamente'
          FROM Citas
          WHERE estado='realizada'
          LIMIT 150;

    ###############################################################
    # CONSUMO DE MATERIALES — VERSIÓN CORREGIDA
    ###############################################################

    - name: Obtener número máximo de items del inventario
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: "SELECT MAX(item_id) AS max_id FROM Inventario;"
      register: inventario_info

    - name: Insertar consumo de materiales (200 citas)
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          SET @maxItem := {{ inventario_info.query_result[0].max_id }};
          INSERT INTO ConsumoMaterial (cita_id, item_id, cantidad_usada)
          SELECT
            cita_id,
            FLOOR(1 + RAND() * @maxItem),
            FLOOR(RAND()*3)+1
          FROM Citas
          LIMIT 200;

    ###############################################################
    # MOVIMIENTOS DE INVENTARIO
    ###############################################################

    - name: Insertar movimientos de inventario (200 movimientos)
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ db.root_password }}"
        login_db: "{{ db.name }}"
        query: |
          INSERT INTO MovimientosInventario (item_id, tipo, cantidad, descripcion)
          SELECT
            FLOOR(RAND()*8)+1,
            ELT(FLOOR(RAND()*3)+1,'entrada','salida','ajuste'),
            FLOOR(RAND()*10)+1,
            'Movimiento generado automáticamente'
          FROM dual
          LIMIT 200;

    ###############################################################
    # MENSAJE FINAL
    ###############################################################

    - name: Mensaje final
      debug:
        msg: "Base de datos poblada con datos demo COMPLETO sin errores ✔✔"

